name: Test
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dfinity/setup-dfx@main
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
      - name: cargo test
        run: |
          cargo clippy --locked --verbose --all-targets --all-features
          cargo test --locked --verbose --workspace -- --nocapture
      - name: npm test
        run: |
          npm ci --ignore-scripts
          npm run typecheck --workspace=@ldclabs/ic_oss_ts
          npm test --workspace=@ldclabs/ic_oss_ts
