name: Test
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dfinity/setup-dfx@main
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
      - name: cargo test
        run: |
          cargo fmt --all -- --check
          cargo clippy --locked --verbose --all-targets --all-features -- -D warnings
          cargo test --locked --verbose --workspace -- --nocapture
      - name: build canister wasm
        run: |
          rustup target add wasm32-unknown-unknown
          RUSTFLAGS="--cfg=getrandom_backend=\"custom\"" cargo build --locked --release --target wasm32-unknown-unknown -p ic_object_store_canister -p ic_oss_bucket -p ic_oss_cluster
      - name: npm test
        run: |
          npm ci --ignore-scripts
          npm run typecheck --workspace=@ldclabs/ic_oss_ts
          npm test --workspace=@ldclabs/ic_oss_ts
